### ISSUE TITLE
Toolbar appears on top of select options

### ISSUE THREAD

**Issue by eduardomart** [bolt/redactor#3]
Redactor toolbar appears to have a higher visibility than a list of items from a select that might be above it.

See sample:
![Screen Shot 2020-09-15 at 2 04 32 AM](https://user-images.githubusercontent.com/1833020/93190514-536a0200-f6f8-11ea-97e5-8d75d461ea11.png)

**Comment by bobdenotter** [comment]
Will be fixed by https://github.com/bolt/core/pull/1875
