### ISSUE TITLE
webpack-encore-bundle breaks redactor

### ISSUE THREAD

**Issue by Alexandre-T** [bolt/redactor#30]
Hello and thank you for the bolt-cms and this redactor.

As soon as you install the webpack-encore-bundle, the redactor field is no more available because JQuery is no more available.

The javascript console ouputs: $ is undefined

Steps to reproduce:
```bash
composer create-project bolt/project myprojectname
cd myprojectname
symfony console doctrine:database:create
symfony console doctrine:schema:create
symfony console bolt:add-user --admin
```
To have a better look, you can init a new git repository and comment this line in .gitignore to check that assets directory isn't updated at all
```.gitignore
#/public/assets/
```
Then install the package without running any scripts (to preserve the assets directory)
```bash
composer require symfony/webpack-encore-bundle --no-scripts
composer recipes:install symfony/webpack-encore-bundle --force -v
```
Then, whatever you follow or not instructions from [the documentation](https://docs.boltcms.io/5.0/howto/encore-setup#jumpbutton), redactor won't work anymore as jQuery and its $ function are no more available.

I don't know if this issue is due to bolt/core implementation or bolt/redactor itself.

**Comment by Alexandre-T** [comment]
After some tests with redactor and article, it seems that it's a bug from the admin panel. There is no links with redactor. I close this issue and create another one in bolt/core.

**Comment by michaelborn** [comment]
The Symfony Encore docs cover this issue in depth, FYI.

https://symfony.com/doc/current/frontend/encore/legacy-applications.html#accessing-jquery-from-outside-of-webpack-javascript-files
