### ISSUE TITLE
Internal server error 500 while uploading image in redactor field

### ISSUE THREAD

**Issue by Wieter** [bolt/redactor#9]
The problem: uploading an image from within the redactor causes an 500 internal server error (and subsequently no image). After some debugging, I found that the culprit originates from #6. 
Apparently, after updating to the latest version, a new configuration item had to be added. This was not mentioned during the update process to do so manually, or was done automagically. I think that either user need to be notified about this in one way or another, or the config file has to be automatically ammended.

Versions installed by composer:
bolt/article                         1.0.14
bolt/assets                          4.1.4
bolt/common                          2.1.9
bolt/core                            4.1.4
bolt/forms                           0.5.0
bolt/newswidget                      1.2.3
bolt/redactor                        1.0.18

![Wytse-NUC-2020-10-30 11_34_07-](https://user-images.githubusercontent.com/20256097/97706939-ccf65d80-1ab6-11eb-8bb8-25aa1f431159.png)

Manual solution:
`config/extensions/bolt-redactor.yaml` had to be updated, by ensuring the following is present:
```
default:
  image:
    thumbnail: 1000^w1000^wmax
```

**Comment by bobdenotter** [comment]
This was fixed in #14
